# Generated by Django 2.0 on 2021-03-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palaces',
            name='place_lat',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='palaces',
            name='place_lon',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='palaces',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
