# Generated by Django 2.0 on 2021-03-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210321_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palaces',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='palaces',
            name='place_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='palaces',
            name='place_lon',
            field=models.FloatField(),
        ),
    ]
