# Generated by Django 2.0 on 2021-03-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210321_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palaces',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
