# Generated by Django 2.0 on 2021-03-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210321_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palaces',
            name='place_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='palaces',
            name='place_lon',
            field=models.FloatField(null=True),
        ),
    ]
