# Generated by Django 2.0 on 2021-03-24 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210321_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('place_lat', models.FloatField(null=True)),
                ('place_lon', models.FloatField(null=True)),
                ('image', models.CharField(default=None, max_length=98)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='palaces',
            name='user',
        ),
        migrations.DeleteModel(
            name='Palaces',
        ),
    ]
