# Generated by Django 2.0 on 2021-03-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210324_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='image',
            field=models.CharField(max_length=98, null=True),
        ),
    ]
