# Generated by Django 2.0 on 2021-03-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210324_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
